-- Chapter 6
-- Working with Sets

-- Exercise 6-1. If set A = {L M N O P} and set B = {P Q R S T}, what sets are generated by the following operations?
• A union B =     {L M N O P Q R S T}
• A union all B = {L M N O P P Q R S T}
• A intersect B = {P}
• A except B =    {L M N O }

-- Exercise 6-2. Write a compound query that finds the first and last names of all actors and customers whose last name starts with L.


-- Exercise 6-3.Sort the results from Exercise 6-2 by the last_name column.
